apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: custom-alerts
  namespace: monitoring
spec:
  groups:
  - name: kubernetes-alerts
    rules:

    - alert: PodCrashLoop
      expr: kube_pod_container_status_restarts_total > 3
      for: 1m
      labels:
        severity: warning
      annotations:
        description: Pod restarting too much

    - alert: HighCPU
      expr: sum(rate(container_cpu_usage_seconds_total[1m])) > 1
      for: 1m
      labels:
        severity: critical
      annotations:
        description: High CPU usage
