apiVersion: v1
kind: ServiceAccount
metadata:
  name: boutique-sa
  namespace: boutique

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: boutique
  name: boutique-role

rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: boutique-binding
  namespace: boutique

subjects:
- kind: ServiceAccount
  name: boutique-sa
  namespace: boutique

roleRef:
  kind: Role
  name: boutique-role
  apiGroup: rbac.authorization.k8s.io