apiVersion: v1
kind: Secret
metadata:
  name: boutique-secret
  namespace: boutique
type: Opaque

stringData:

  REDIS_ADDR: redis:6379
  EMAIL_SERVICE_ADDR: emailservice:8080
  PAYMENT_SERVICE_ADDR: paymentservice:50051
  SHIPPING_SERVICE_ADDR: shippingservice:50051