apiVersion: v1
kind: Pod
metadata:
  name: security-template
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  containers:
  - name: example
    image: nginx

    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true

      capabilities:
        drop:
        - ALL