apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      serviceAccountName: boutique-sa

      imagePullSecrets:
        - name: ecr-secret
      
      # POD security context (correct place)
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: cartservice
          image: 998948477550.dkr.ecr.eu-west-2.amazonaws.com/boutique-cart:v1
          imagePullPolicy: Always

          # container security context (correct place)
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL

          ports:
            - containerPort: 7070
          env:
            - name: REDIS_ADDR
              value: "redis:6379"
            - name: PORT
              value: "7070"