apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      serviceAccountName: boutique-sa

      imagePullSecrets:
        - name: ecr-secret
      
      # POD security context (correct place)
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
          
      containers:
        - name: paymentservice
          image: 998948477550.dkr.ecr.eu-west-2.amazonaws.com/boutique-payment:v5
          imagePullPolicy: Always

          # container security context (correct place)
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL

          ports:
            - containerPort: 50051